package tetra

// Field widths and optional branches checked against the supplied SDRSharp plugin.
var releaseRules = []fieldRule{
	{"Call_identifier", 14, "Direct", "", 0, 0},
	{"Disconnect_cause", 5, "Direct", "", 0, 0},
	{"Options_bit", 1, "Options_bit", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Notification_indicator", 6, "Direct", "", 0, 0},
	{"More_bit", 1, "More_bit", "", 0, 0},
}
var ceasedRules = []fieldRule{
	{"Call_identifier", 14, "Direct", "", 0, 0},
	{"Transmission_request_permission", 1, "Direct", "", 0, 0},
	{"Options_bit", 1, "Options_bit", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Notification_indicator", 6, "Direct", "", 0, 0},
	{"More_bit", 1, "More_bit", "", 0, 0},
}
var grantRules = []fieldRule{
	{"Call_identifier", 14, "Direct", "", 0, 0},
	{"Transmission_grant", 2, "Direct", "", 0, 0},
	{"Transmission_request_permission", 1, "Direct", "", 0, 0},
	{"Encryption_control", 1, "Direct", "", 0, 0},
	{"Reserved", 1, "Direct", "", 0, 0},
	{"Options_bit", 1, "Options_bit", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Notification_indicator", 6, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 3},
	{"Transmitting_party_type_identifier", 2, "Direct", "", 0, 0},
	{"Transmitting_party_address_SSI", 24, "Direct", "", 0, 0},
	{"Transmitting_party_extension", 24, "Switch", "Transmitting_party_type_identifier", 2, 0},
	{"More_bit", 1, "More_bit", "", 0, 0},
}
var setupRules = []fieldRule{
	{"Call_identifier", 14, "Direct", "", 0, 0},
	{"Call_time_out", 4, "Direct", "", 0, 0},
	{"Hook_method", 1, "Direct", "", 0, 0},
	{"Simplex_duplex", 1, "Direct", "", 0, 0},
	{"Basic_service_Circuit_mode_type", 3, "Direct", "", 0, 0},
	{"Basic_service_Encryption_flag", 1, "Direct", "", 0, 0},
	{"Basic_service_Communication_type", 2, "Direct", "", 0, 0},
	{"Basic_service_Slots_per_frame", 2, "SwitchNot", "Basic_service_Circuit_mode_type", 0, 0},
	{"Basic_service_Speech_service", 2, "Switch", "Basic_service_Circuit_mode_type", 0, 0},
	{"Transmission_grant", 2, "Direct", "", 0, 0},
	{"Transmission_request_permission", 1, "Direct", "", 0, 0},
	{"Call_priority", 4, "Direct", "", 0, 0},
	{"Options_bit", 1, "Options_bit", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Notification_indicator", 6, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Temporary_address", 24, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 3},
	{"Calling_party_type_identifier", 2, "Direct", "", 0, 0},
	{"Calling_party_address_SSI", 24, "Direct", "", 0, 0},
	{"Calling_party_extension", 24, "Switch", "Calling_party_type_identifier", 2, 0},
	{"More_bit", 1, "More_bit", "", 0, 0},
}
var infoRules = []fieldRule{
	{"Call_identifier", 14, "Direct", "", 0, 0},
	{"Reset_Call_time_out", 1, "Direct", "", 0, 0},
	{"Poll_request", 1, "Direct", "", 0, 0},
	{"Options_bit", 1, "Options_bit", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"New_Call_Identifier", 14, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Call_time_out", 4, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Call_time_out_setup_phase", 3, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Call_ownership", 1, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Modify", 9, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Call_status", 3, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Temporary_address", 24, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Notification_indicator", 6, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Poll_response_percentage", 6, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Poll_response_number", 6, "Direct", "", 0, 0},
	{"More_bit", 1, "More_bit", "", 0, 0},
}
var connectRules = []fieldRule{
	{"Call_identifier", 14, "Direct", "", 0, 0},
	{"Call_time_out", 4, "Direct", "", 0, 0},
	{"Hook_method", 1, "Direct", "", 0, 0},
	{"Simplex_duplex", 1, "Direct", "", 0, 0},
	{"Transmission_grant", 2, "Direct", "", 0, 0},
	{"Transmission_request_permission", 1, "Direct", "", 0, 0},
	{"Call_ownership", 1, "Direct", "", 0, 0},
	{"Options_bit", 1, "Options_bit", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Call_priority", 4, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 5},
	{"Basic_service_Circuit_mode_type", 3, "Direct", "", 0, 0},
	{"Basic_service_Encryption_flag", 1, "Direct", "", 0, 0},
	{"Basic_service_Communication_type", 2, "Direct", "", 0, 0},
	{"Basic_service_Slots_per_frame", 2, "SwitchNot", "Basic_service_Circuit_mode_type", 0, 0},
	{"Basic_service_Speech_service", 2, "Switch", "Basic_service_Circuit_mode_type", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Temporary_address", 24, "Direct", "", 0, 0},
	{"Presence_bit", 1, "Presence_bit", "", 0, 1},
	{"Notification_indicator", 6, "Direct", "", 0, 0},
	{"More_bit", 1, "More_bit", "", 0, 0},
}
var forwardRules = []fieldRule{
	{"Delivery_report_request", 2, "Direct", "", 0, 0},
	{"Service_selection", 1, "Direct", "", 0, 0},
	{"Storage_forward_control", 1, "Direct", "", 0, 0},
	{"Message_reference", 8, "Direct", "", 0, 0},
	{"Reserved", 0, "Jump", "Storage_forward_control", 0, 99},
	{"Validity_period", 5, "Direct", "", 0, 0},
	{"Forward_address_type", 3, "Direct", "", 0, 0},
	{"Forward_short_address", 8, "Switch", "Forward_address_type", 0, 0},
	{"Forward_address_SSI", 24, "Switch", "Forward_address_type", 1, 0},
	{"Forward_address_SSI", 24, "Switch", "Forward_address_type", 2, 0},
	{"Forward_address_extension", 24, "Switch", "Forward_address_type", 2, 0},
	{"Reserved", 0, "JumpNot", "Forward_address_type", 3, 99},
	{"Number_subscriber_number_digits", 8, "Direct", "", 0, 0},
	{"Reserved", 8, "Switch", "Number_subscriber_number_digits", 1, 0},
	{"Reserved", 8, "Switch", "Number_subscriber_number_digits", 2, 0},
	{"Reserved", 16, "Switch", "Number_subscriber_number_digits", 3, 0},
	{"Reserved", 16, "Switch", "Number_subscriber_number_digits", 4, 0},
	{"Reserved", 24, "Switch", "Number_subscriber_number_digits", 5, 0},
	{"Reserved", 24, "Switch", "Number_subscriber_number_digits", 6, 0},
	{"Reserved", 32, "Switch", "Number_subscriber_number_digits", 7, 0},
	{"Reserved", 32, "Switch", "Number_subscriber_number_digits", 8, 0},
	{"Reserved", 40, "Switch", "Number_subscriber_number_digits", 9, 0},
	{"Reserved", 40, "Switch", "Number_subscriber_number_digits", 10, 0},
	{"Reserved", 48, "Switch", "Number_subscriber_number_digits", 11, 0},
	{"Reserved", 48, "Switch", "Number_subscriber_number_digits", 12, 0},
	{"Reserved", 56, "Switch", "Number_subscriber_number_digits", 13, 0},
	{"Reserved", 56, "Switch", "Number_subscriber_number_digits", 14, 0},
	{"Reserved", 64, "Switch", "Number_subscriber_number_digits", 15, 0},
	{"Reserved", 64, "Switch", "Number_subscriber_number_digits", 16, 0},
	{"Reserved", 72, "Switch", "Number_subscriber_number_digits", 17, 0},
	{"Reserved", 72, "Switch", "Number_subscriber_number_digits", 18, 0},
	{"Reserved", 80, "Switch", "Number_subscriber_number_digits", 19, 0},
	{"Reserved", 80, "Switch", "Number_subscriber_number_digits", 20, 0},
	{"Reserved", 88, "Switch", "Number_subscriber_number_digits", 21, 0},
	{"Reserved", 88, "Switch", "Number_subscriber_number_digits", 22, 0},
	{"Reserved", 96, "Switch", "Number_subscriber_number_digits", 23, 0},
	{"Reserved", 96, "Switch", "Number_subscriber_number_digits", 24, 0},
}
var reportRules = []fieldRule{
	{"Acknowledgement_required", 1, "Direct", "", 0, 0},
	{"Reserved", 2, "Direct", "", 0, 0},
	{"Storage_forward_control", 1, "Direct", "", 0, 0},
	{"Delivery_status", 8, "Direct", "", 0, 0},
	{"Message_reference", 8, "Direct", "", 0, 0},
	{"Presence_bit", 0, "Jump", "Storage_forward_control", 0, 99},
	{"Validity_period", 5, "Direct", "", 0, 0},
	{"Forward_address_type", 3, "Direct", "", 0, 0},
	{"Forward_short_address", 8, "Switch", "Forward_address_type", 0, 0},
	{"Forward_address_SSI", 24, "Switch", "Forward_address_type", 1, 0},
	{"Forward_address_SSI", 24, "Switch", "Forward_address_type", 2, 0},
	{"Forward_address_extension", 24, "Switch", "Forward_address_type", 2, 0},
	{"Reserved", 0, "JumpNot", "Forward_address_type", 3, 99},
	{"Number_subscriber_number_digits", 8, "Direct", "", 0, 0},
	{"Reserved", 8, "Switch", "Number_subscriber_number_digits", 1, 0},
	{"Reserved", 8, "Switch", "Number_subscriber_number_digits", 2, 0},
	{"Reserved", 16, "Switch", "Number_subscriber_number_digits", 3, 0},
	{"Reserved", 16, "Switch", "Number_subscriber_number_digits", 4, 0},
	{"Reserved", 24, "Switch", "Number_subscriber_number_digits", 5, 0},
	{"Reserved", 24, "Switch", "Number_subscriber_number_digits", 6, 0},
	{"Reserved", 32, "Switch", "Number_subscriber_number_digits", 7, 0},
	{"Reserved", 32, "Switch", "Number_subscriber_number_digits", 8, 0},
	{"Reserved", 40, "Switch", "Number_subscriber_number_digits", 9, 0},
	{"Reserved", 40, "Switch", "Number_subscriber_number_digits", 10, 0},
	{"Reserved", 48, "Switch", "Number_subscriber_number_digits", 11, 0},
	{"Reserved", 48, "Switch", "Number_subscriber_number_digits", 12, 0},
	{"Reserved", 56, "Switch", "Number_subscriber_number_digits", 13, 0},
	{"Reserved", 56, "Switch", "Number_subscriber_number_digits", 14, 0},
	{"Reserved", 64, "Switch", "Number_subscriber_number_digits", 15, 0},
	{"Reserved", 64, "Switch", "Number_subscriber_number_digits", 16, 0},
	{"Reserved", 72, "Switch", "Number_subscriber_number_digits", 17, 0},
	{"Reserved", 72, "Switch", "Number_subscriber_number_digits", 18, 0},
	{"Reserved", 80, "Switch", "Number_subscriber_number_digits", 19, 0},
	{"Reserved", 80, "Switch", "Number_subscriber_number_digits", 20, 0},
	{"Reserved", 88, "Switch", "Number_subscriber_number_digits", 21, 0},
	{"Reserved", 88, "Switch", "Number_subscriber_number_digits", 22, 0},
	{"Reserved", 96, "Switch", "Number_subscriber_number_digits", 23, 0},
	{"Reserved", 96, "Switch", "Number_subscriber_number_digits", 24, 0},
}
var textRules = []fieldRule{
	{"Time_stamp_used", 1, "Direct", "", 0, 0},
	{"Text_coding_scheme", 7, "Direct", "", 0, 0},
	{"Timeframe_type", 2, "Switch", "Time_stamp_used", 1, 0},
	{"Reserved", 2, "Switch", "Time_stamp_used", 1, 0},
	{"Month", 4, "Switch", "Time_stamp_used", 1, 0},
	{"Day", 5, "Switch", "Time_stamp_used", 1, 0},
	{"Hour", 5, "Switch", "Time_stamp_used", 1, 0},
	{"Minute", 6, "Switch", "Time_stamp_used", 1, 0},
}
